// ACCEL.sv

`default_nettype none
`include "rtl_macros.svh"


module ACCEL 
(
input  logic            ACCEL_CLK, ACCEL_RSTN,
output logic            IRQ,
ahb_s_intf.source   S
);


//always_comb IRQ = 1'b0;

reg_intf      #(.DW(32),.AW(32)) pregs();

//---------------------------------------------------------
// AHB sub interface
//---------------------------------------------------------
// Main AHB bus sub interface (HCLK domain)


ahb_sub #(.DW(32), .AW(32)) u_accel
( 
.clk        (ACCEL_CLK),
.rstn       (ACCEL_RSTN),
.S          (S),
.regs      (pregs.source)
);


//---------------------------------------------------------
// pregs
//---------------------------------------------------------
// Control and Status registers (CSRs) in HCLK domain.
// These are generated automatically.

// Copy content of ./pregs/output/pregs.inst.sv here
// VGEN START: Autogenerated by /ee/166/CHIPKIT/tools/vgen/bin/vgen.py on 17:07:38 09/04/2026

// START
// VGEN START: Autogenerated by /ee/166/CHIPKIT/tools/vgen/bin/vgen.py on 21:57:22 14/04/2026

// START
logic [3:0] CTRL;
logic [3:0] STATUS;
logic [31:0] PC_VALUE;
logic [31:0] IMEM_ADDR;
logic [31:0] IMEM_DATA;
logic [31:0] DMEM_ADDR;
logic [31:0] DMEM_WDATA;
logic [31:0] DMEM_RDATA;

pregs u_pregs (

// clocks and resets
.clk(ACCEL_CLK),
.rstn(ACCEL_RSTN),

// Synchronous register interface
.regbus           (pregs.sink),

// reg file signals
.CTRL(CTRL[3:0])        /* idx 4 */,
.STATUS(STATUS[3:0])    /* idx 5 */,
.PC_VALUE(PC_VALUE[31:0])       /* idx 6 */,
.IMEM_ADDR(IMEM_ADDR[31:0])     /* idx 7 */,
.IMEM_DATA(IMEM_DATA[31:0])     /* idx 8 */,
.DMEM_ADDR(DMEM_ADDR[31:0])     /* idx 9 */,
.DMEM_WDATA(DMEM_WDATA[31:0])   /* idx 10 */,
.DMEM_RDATA(DMEM_RDATA[31:0])   /* idx 11 */

);
// END

// VGEN END: Autogenerated by /ee/166/CHIPKIT/tools/vgen/bin/vgen.py on 21:57:22 14/04/2026

// END

// VGEN END: Autogenerated by /ee/166/CHIPKIT/tools/vgen/bin/vgen.py on 17:07:38 09/04/2026

// State definitions like FIR
localparam logic [3:0] IDLE      = 4'h1;
localparam logic [3:0] LOAD_PROG = 4'h2;  // Load program to IMEM
localparam logic [3:0] RUN       = 4'h4;  // CPU running
localparam logic [3:0] HALT      = 4'h8;  // CPU halt

// write detection
logic imem_data_wen; //ahb write to imem data register
logic dmem_wdata_wen;
assign imem_data_wen = pregs.write_en & (pregs.addr[9:2] == 8'd8);
assign dmem_wdata_wen = pregs.write_en & (pregs.addr[9:2] == 8'd10);

// instruction mem assuming harvard arch
logic [7:0] imem_rdata [4]; // read data line
logic [31:0] cpu_instruction;
logic [31:0] cpu_pc;
logic cpu_running;

// IMEM address mux to control if PC controls imem or external for loading
// code
logic [31:0] imem_addr_mux;
assign imem_addr_mux = cpu_running ? cpu_pc : IMEM_ADDR;

// IMEM write happens only during the loading state
logic imem_write; // allowed to write mem
assign imem_write = imem_data_wen && (CTRL == LOAD_PROG);

// split imem data into bytes cus memory module takes in bytes
logic [7:0] imem_wdata [4]; //the bytes to write
assign imem_wdata[0] = IMEM_DATA[7:0];
assign imem_wdata[1] = IMEM_DATA[15:8];
assign imem_wdata[2] = IMEM_DATA[23:16];
assign imem_wdata[3] = IMEM_DATA[31:24];

MemoryModule u_imem (
        .clk (ACCEL_CLK),
        .address (imem_addr_mux),
        .writeData (imem_wdata),
        .memWrite (imem_write),
        .memRead (cpu_running),
        .byteWriteEnable(4'b1111), // 32 bit instructions
        .readData (imem_rdata),
        .OOBRead (),
        .OOBWrite (),
        .debug_mem_contents_low (),
	.debug_mem_contents_high ()
);

// combine the bytes into the instruction
assign cpu_instruction = {imem_rdata[3], imem_rdata[2], imem_rdata[1], imem_rdata[0]};

// data memory
logic [7:0] dmem_rdata [4];

// CPU DMEM memory interface
logic [31:0] cpu_dmem_addr;
logic [7:0] cpu_dmem_wdata [4];
logic cpu_dmem_write;
logic cpu_dmem_read;
logic [3:0] cpu_dmem_byte_write_enable;

// mux for give cpu access dmem when running, but other access outside of that
logic [31:0] dmem_addr_mux;
logic [7:0] dmem_wdata_mux [4];
logic dmem_write_mux;
logic dmem_read_mux;
logic [3:0] dmem_byte_write_enable_mux;

always_comb begin
	if (cpu_running && (cpu_dmem_write || cpu_dmem_read)) begin
		dmem_addr_mux = cpu_dmem_addr;
            	dmem_wdata_mux = cpu_dmem_wdata;
           	dmem_write_mux = cpu_dmem_write;
            	dmem_read_mux  = cpu_dmem_read;
            	dmem_byte_write_enable_mux = cpu_dmem_byte_write_enable;
        end else begin
            	// Outside DMEM AHB access
            	dmem_addr_mux = DMEM_ADDR;
            	dmem_wdata_mux[0] = DMEM_WDATA[7:0];
            	dmem_wdata_mux[1] = DMEM_WDATA[15:8];
            	dmem_wdata_mux[2] = DMEM_WDATA[23:16];
            	dmem_wdata_mux[3] = DMEM_WDATA[31:24];
            	dmem_write_mux = dmem_wdata_wen && (CTRL != RUN);
            	dmem_read_mux = 1'b1;
            	dmem_byte_write_enable_mux = 4'b1111;
	end
end

MemoryModule u_dmem (
	.clk (ACCEL_CLK),
        .address (dmem_addr_mux),
        .writeData (dmem_wdata_mux),
        .memWrite (dmem_write_mux),
        .memRead (dmem_read_mux),
        .byteWriteEnable(dmem_byte_write_enable_mux),
        .readData (dmem_rdata),
        .OOBRead(),
        .OOBWrite(),
        .debug_mem_contents_low (),
        .debug_mem_contents_high()
);

assign DMEM_RDATA = {dmem_rdata[3], dmem_rdata[2], dmem_rdata[1], dmem_rdata[0]};

// State machine

assign cpu_running = (CTRL == RUN);

//cpu

top u_cpu(
	.sysclk (ACCEL_CLK),
	.sysreset (ACCEL_RSTN && (CTRL != IDLE)),
	.cpu_enable (cpu_running),
	.instructionAddr(cpu_pc),
	.instruction (cpu_instruction),
	.dmem_addr (cpu_dmem_addr),
	.dmem_wdata (cpu_dmem_wdata),
	.dmem_write (cpu_dmem_write),
        .dmem_read (cpu_dmem_read),
        .dmem_byte_write_enable (cpu_dmem_byte_write_enable),
        .dmem_rdata (dmem_rdata)
);

// status and irq
assign STATUS[0] = cpu_running;
assign STATUS[1] = (CTRL == HALT);
assign STATUS[2] = 1'b0; // for errors or something we can decide
assign STATUS[3] = 1'b0; // another one

assign PC_VALUE = cpu_pc;
assign IRQ = (CTRL==HALT); // maybe change this to when program is done but idk how to do that

endmodule

`default_nettype wire

