// ACCEL.sv
// modified last on 4/22/26

`default_nettype none
`include "rtl_macros.svh"


module ACCEL 
(
input  logic            ACCEL_CLK, ACCEL_RSTN,
output logic            IRQ,
ahb_s_intf.source   S,

input  logic [31:0]     cpu_pc,
output logic [31:0]     cpu_instruction,
input  logic [31:0]     cpu_dmem_addr,
input  logic [31:0]     cpu_dmem_wdata,
input  logic            cpu_dmem_write,
input  logic            cpu_dmem_read,
input  logic [3:0]      cpu_dmem_byte_write_enable,
output logic [31:0]     cpu_dmem_rdata
);


//always_comb IRQ = 1'b0;

reg_intf      #(.DW(32),.AW(32)) pregs();

//---------------------------------------------------------
// AHB sub interface
//---------------------------------------------------------
// Main AHB bus sub interface (HCLK domain)


ahb_sub #(.DW(32), .AW(32)) u_accel
( 
.clk        (ACCEL_CLK),
.rstn       (ACCEL_RSTN),
.S          (S),
.regs      (pregs.source)
);


//---------------------------------------------------------
// pregs
//---------------------------------------------------------
// Control and Status registers (CSRs) in HCLK domain.
// These are generated automatically.

// Copy content of ./pregs/output/pregs.inst.sv here
// VGEN START: Autogenerated by /ee/166/CHIPKIT/tools/vgen/bin/vgen.py on 17:07:38 09/04/2026

// START
// VGEN START: Autogenerated by /ee/166/CHIPKIT/tools/vgen/bin/vgen.py on 21:57:22 14/04/2026

// START
logic [3:0] CTRL;
logic [3:0] STATUS;
logic [31:0] PC_VALUE;
logic [31:0] IMEM_ADDR;
logic [31:0] IMEM_DATA;
logic [31:0] DMEM_ADDR;
logic [31:0] DMEM_WDATA;
logic [31:0] DMEM_RDATA;

pregs u_pregs (

// clocks and resets
.clk(ACCEL_CLK),
.rstn(ACCEL_RSTN),

// Synchronous register interface
.regbus           (pregs.sink),

// reg file signals
.CTRL(CTRL[3:0])        /* idx 4 */,
.STATUS(STATUS[3:0])    /* idx 5 */,
.PC_VALUE(PC_VALUE[31:0])       /* idx 6 */,
.IMEM_ADDR(IMEM_ADDR[31:0])     /* idx 7 */,
.IMEM_DATA(IMEM_DATA[31:0])     /* idx 8 */,
.DMEM_ADDR(DMEM_ADDR[31:0])     /* idx 9 */,
.DMEM_WDATA(DMEM_WDATA[31:0])   /* idx 10 */,
.DMEM_RDATA(DMEM_RDATA[31:0])   /* idx 11 */

);
// END

// VGEN END: Autogenerated by /ee/166/CHIPKIT/tools/vgen/bin/vgen.py on 21:57:22 14/04/2026

// END

// VGEN END: Autogenerated by /ee/166/CHIPKIT/tools/vgen/bin/vgen.py on 17:07:38 09/04/2026

// State definitions like FIR
localparam logic [3:0] IDLE      = 4'h1;
localparam logic [3:0] LOAD_PROG = 4'h2;  // Load program to IMEM
localparam logic [3:0] RUN       = 4'h4;  // CPU running
localparam logic [3:0] HALT      = 4'h8;  // CPU halt

// write detection
logic imem_data_wen; //ahb write to imem data register
logic dmem_wdata_wen;
assign imem_data_wen = pregs.write_en && (pregs.addr[9:2] == 8'd8);
assign dmem_wdata_wen = pregs.write_en && (pregs.addr[9:2] == 8'd10);

// instruction mem assuming harvard arch
logic cpu_running;
assign cpu_running = 1'b1;

// IMEM address mux to control if PC controls imem or external for loading
// code
logic [31:0] imem_addr_mux;
assign imem_addr_mux = cpu_running ? cpu_pc : IMEM_ADDR;

InstructionMemory u_imem (
        .address (imem_addr_mux),
        .instruction (cpu_instruction)
);

// mux for give cpu access dmem when running, but other access outside of that
logic [31:0] dmem_addr_mux;
logic [31:0] dmem_wdata_mux;
logic dmem_write_mux;
logic [3:0] dmem_byte_write_enable_mux;
logic [31:0] dmem_rdata;
assign cpu_dmem_rdata = dmem_rdata;

always_comb begin
	if (cpu_running) begin
		dmem_addr_mux = cpu_dmem_addr;
            	dmem_wdata_mux = cpu_dmem_wdata;
           	dmem_write_mux = cpu_dmem_write;
            	dmem_byte_write_enable_mux = cpu_dmem_byte_write_enable;
        end else begin
            	// Outside DMEM AHB access
            	dmem_addr_mux = DMEM_ADDR;
            	dmem_wdata_mux = DMEM_WDATA;
            	dmem_write_mux = dmem_wdata_wen && (CTRL != RUN);
            	dmem_byte_write_enable_mux = 4'b1111;
	end
end

MemoryModule u_dmem (
	.clk (ACCEL_CLK),
        .address (dmem_addr_mux),
        .writeData (dmem_wdata_mux),
        .memWrite (dmem_write_mux),
        .byteWriteEnable(dmem_byte_write_enable_mux),
        .readData (dmem_rdata)
);

assign DMEM_RDATA = dmem_rdata;

endmodule

`default_nettype wire
