// VGEN START: Autogenerated by /ee/166/CHIPKIT/tools/vgen/bin/vgen.py on 12:08:10 03/05/2026

// Paul Whatmough Nov 2015


// VGEN: HEADER
// Register file contents:
//{'name': 'CTRL', 'idx': '4', 'nbits': '4', 'start': '0', 'access': 'rw', 'test': '0', 'rval': '0x1', 'desc': 'Control: 1=IDLE 2=LOAD 4=RUN 8=HALT'}
//{'name': 'STATUS', 'idx': '5', 'nbits': '4', 'start': '0', 'access': 'r', 'test': '0', 'rval': '0x0', 'desc': 'Status: [0]=running [1]=halted [2]=done'}
//{'name': 'PC_VALUE', 'idx': '6', 'nbits': '32', 'start': '0', 'access': 'r', 'test': '0', 'rval': '0x0', 'desc': 'Current program counter'}
//{'name': 'IMEM_ADDR', 'idx': '7', 'nbits': '32', 'start': '0', 'access': 'rw', 'test': '0', 'rval': '0x0', 'desc': 'IMEM write address'}
//{'name': 'IMEM_DATA', 'idx': '8', 'nbits': '32', 'start': '0', 'access': 'rw', 'test': '0', 'rval': '0x0', 'desc': 'IMEM write data (triggers store)'}
//{'name': 'DMEM_ADDR', 'idx': '9', 'nbits': '32', 'start': '0', 'access': 'rw', 'test': '0', 'rval': '0x0', 'desc': 'DMEM access address'}
//{'name': 'DMEM_WDATA', 'idx': '10', 'nbits': '32', 'start': '0', 'access': 'rw', 'test': '0', 'rval': '0x0', 'desc': 'DMEM write data'}
//{'name': 'DMEM_RDATA', 'idx': '11', 'nbits': '32', 'start': '0', 'access': 'r', 'test': '0', 'rval': '0x0', 'desc': 'DMEM read data'}




module

// VGEN: MODULE NAME
pregs

(

// clocks and resets
input  logic     clk,
input  logic     rstn,

// Synchronous register interface
reg_intf.sink regbus,


// VGEN: INPUTS TO REGS
input  logic [3:0] STATUS,      /* idx #1: Status: [0]=running [1]=halted [2]=done */
input  logic [31:0] PC_VALUE,   /* idx #2: Current program counter */
input  logic [31:0] DMEM_RDATA, /* idx #7: DMEM read data */


// VGEN: OUTPUTS FROM REGS
output logic [3:0] CTRL  /* idx #0: Control: 1=IDLE 2=LOAD 4=RUN 8=HALT */,
output logic [31:0] IMEM_ADDR    /* idx #3: IMEM write address */,
output logic [31:0] IMEM_DATA    /* idx #4: IMEM write data (triggers store) */,
output logic [31:0] DMEM_ADDR    /* idx #5: DMEM access address */,
output logic [31:0] DMEM_WDATA   /* idx #6: DMEM write data */

);


//------------------------------------------------------------------------------
// Register write
//------------------------------------------------------------------------------

// VGEN: REG WRITE
// idx #0
logic [3:0] CTRL_reg;
always@(posedge clk or negedge rstn) begin
  if(~rstn) begin
    CTRL_reg[3:0] <= 4'h1;
  end else begin
    if(regbus.write_en & (regbus.addr[9:2]==8'h4)) CTRL_reg[3:0] <= regbus.wdata[3:0];
  end
end
assign CTRL[3:0] = CTRL_reg[3:0];

// idx #3
logic [31:0] IMEM_ADDR_reg;
always@(posedge clk or negedge rstn) begin
  if(~rstn) begin
    IMEM_ADDR_reg[31:0] <= '0;
  end else begin
    if(regbus.write_en & (regbus.addr[9:2]==8'h7)) IMEM_ADDR_reg[31:0] <= regbus.wdata[31:0];
  end
end
assign IMEM_ADDR[31:0] = IMEM_ADDR_reg[31:0];

// idx #4
logic [31:0] IMEM_DATA_reg;
always@(posedge clk or negedge rstn) begin
  if(~rstn) begin
    IMEM_DATA_reg[31:0] <= '0;
  end else begin
    if(regbus.write_en & (regbus.addr[9:2]==8'h8)) IMEM_DATA_reg[31:0] <= regbus.wdata[31:0];
  end
end
assign IMEM_DATA[31:0] = IMEM_DATA_reg[31:0];

// idx #5
logic [31:0] DMEM_ADDR_reg;
always@(posedge clk or negedge rstn) begin
  if(~rstn) begin
    DMEM_ADDR_reg[31:0] <= '0;
  end else begin
    if(regbus.write_en & (regbus.addr[9:2]==8'h9)) DMEM_ADDR_reg[31:0] <= regbus.wdata[31:0];
  end
end
assign DMEM_ADDR[31:0] = DMEM_ADDR_reg[31:0];

// idx #6
logic [31:0] DMEM_WDATA_reg;
always@(posedge clk or negedge rstn) begin
  if(~rstn) begin
    DMEM_WDATA_reg[31:0] <= '0;
  end else begin
    if(regbus.write_en & (regbus.addr[9:2]==8'ha)) DMEM_WDATA_reg[31:0] <= regbus.wdata[31:0];
  end
end
assign DMEM_WDATA[31:0] = DMEM_WDATA_reg[31:0];



//------------------------------------------------------------------------------
// Register read
//------------------------------------------------------------------------------


logic [31:0] rdata_o;

always @*
begin
  if (regbus.read_en)
  begin
    rdata_o[31:0] = 32'h00000000;

    // VGEN: REG READ
    if(regbus.addr[9:2]==8'h4)     if(regbus.addr[9:2]==8'h4) rdata_o[3:0] = CTRL[3:0];  // idx #0
    if(regbus.addr[9:2]==8'h5)     if(regbus.addr[9:2]==8'h5) rdata_o[3:0] = STATUS[3:0];        // idx #1
    if(regbus.addr[9:2]==8'h6)     if(regbus.addr[9:2]==8'h6) rdata_o[31:0] = PC_VALUE[31:0];    // idx #2
    if(regbus.addr[9:2]==8'h7)     if(regbus.addr[9:2]==8'h7) rdata_o[31:0] = IMEM_ADDR[31:0];   // idx #3
    if(regbus.addr[9:2]==8'h8)     if(regbus.addr[9:2]==8'h8) rdata_o[31:0] = IMEM_DATA[31:0];   // idx #4
    if(regbus.addr[9:2]==8'h9)     if(regbus.addr[9:2]==8'h9) rdata_o[31:0] = DMEM_ADDR[31:0];   // idx #5
    if(regbus.addr[9:2]==8'ha)     if(regbus.addr[9:2]==8'ha) rdata_o[31:0] = DMEM_WDATA[31:0];  // idx #6
    if(regbus.addr[9:2]==8'hb)     if(regbus.addr[9:2]==8'hb) rdata_o[31:0] = DMEM_RDATA[31:0];  // idx #7

  end
  else
  begin
    rdata_o[31:0] = {32'h00000000};
  end
end

assign regbus.rdata[31:0] = rdata_o[31:0];


//------------------------------------------------------------------------------
//
//------------------------------------------------------------------------------




endmodule
// VGEN END: Autogenerated by /ee/166/CHIPKIT/tools/vgen/bin/vgen.py on 12:08:10 03/05/2026


